#
# ansible galaxy requirements
#
- src: geerlingguy.swap
  version: 1.0.0

#
# wcm-io-devops requirements
#
- name: wcm_io_devops.aem_cms
  version: 1.0.0
- name: wcm_io_devops.aem_dispatcher
  version: 1.0.0
- name: wcm_io_devops.aem_dispatcher_flush
  version: 1.0.0
- name: wcm_io_devops.aem_security
  version: 1.1.0
- name: wcm_io_devops.aem_service
  version: 1.1.0
- name: wcm_io_devops.conga_aem_cms
  version: 1.0.0
- name: wcm_io_devops.conga_bundle_files
  version: 1.1.0
- name: wcm_io_devops.conga_aem_dispatcher
  version: 1.0.0
- name: wcm_io_devops.conga_aem_dispatcher_flush
  version: 1.0.0
- name: wcm_io_devops.conga_aem_dispatcher_smoke_test
  version: 1.0.0
- name: wcm_io_devops.conga_aem_packages
  version: 1.1.0
- name: wcm_io_devops.conga_aem_smoke_test
  version: 1.0.0
- name: wcm_io_devops.conga_ansible_controlhost
  version: 2.0.0
- name: wcm_io_devops.conga_maven
  version: 1.0.0
- name: wcm_io_devops.conga_facts
  version: 1.0.0
- name: wcm_io_devops.conga_files
  version: 1.0.0
- name: wcm_io_devops.conga_host_facts
  version: 1.0.0
- name: wcm_io_devops.apache
  version: 3.0.3-1
